"use client"; // Add this directive for client component

import { Inter } from "next/font/google";
import "./globals.css";
import { ApolloProvider } from "@apollo/client";
import client from "./lib/apolloClient"; // Import the client
import { AuthProvider } from "./context/AuthContext"; // Import AuthProvider
import Header from "./components/Header"; // Import Header

const inter = Inter({ subsets: ["latin"] });

// Metadata cannot be used in a client component, so we remove it or handle it differently if needed.
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ApolloProvider client={client}>
          <AuthProvider client={client}>
            <div className="min-h-screen bg-gray-100">
              <Header />
              <main className="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
                {children}
              </main>
            </div>
          </AuthProvider>
        </ApolloProvider>
      </body>
    </html>
  );
}
